### ISSUE TITLE
AuthProviderSystemErrorException ?

### ISSUE THREAD

**Issue by danergo** [SeppPenner/WindowsHello#6]
I tried running the sample in readme (I'm on SDK7, Win11), and I always got the above exception:

![image](https://user-images.githubusercontent.com/11708344/216310549-b68ee62c-a7e0-4d68-8bb5-f4e49a4b3332.png)

Is there a way to fix this? Am I missing something?

![image](https://user-images.githubusercontent.com/11708344/216329893-12b89fd5-f048-4789-85e4-53890f5d3a7d.png)

Thank you.

**Comment by danergo** [comment]
When I tried with your other repo (https://github.com/SeppPenner/WindowsHelloChanges), it worked, just I have no idea if that contains the fix mentioned in #3.

**Comment by danergo** [comment]
I have found a reference for error 0x80090027:

> Caller provided a wrong parameter. If third-party code receives this error, they must change their code.

Source: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md

But I couldn't realize which parameter could go wrong, even by comparing with your "HelloChanges" repository which seems working.

**Comment by danergo** [comment]
I tried changing the persistent key name, to be sure that earlier runs with different configurations don't mess up with this actual version, but it didn't help.

**Comment by danergo** [comment]
If I change this line:

https://github.com/SeppPenner/WindowsHello/blob/bcfca90309f73d80bc59ec1b9f27b690a8fa9080/src/WindowsHello/WinHelloProvider.cs#L233

to

    null,

It works as intended:

![image](https://user-images.githubusercontent.com/11708344/216550085-1f769f7f-3b09-406a-9c6c-105f9c524fa6.png)

To eliminate the compiler warning of "CS8625: Cannot convert null literal to non-nullable reference type", you'll have to change this line:

https://github.com/SeppPenner/WindowsHello/blob/bcfca90309f73d80bc59ec1b9f27b690a8fa9080/src/WindowsHello/WinHelloProvider.cs#L538

to

    byte[]? pbOutput,

Which, according to official docs, is perfectly matching with the signature of this parameter (quoted from https://learn.microsoft.com/en-us/windows/win32/api/ncrypt/nf-ncrypt-ncryptencrypt#parameters):

> [out] pbOutput
> ...
> If this parameter is NULL, this function will calculate the size needed for the encrypted data and return the size in the location pointed to by the pcbResult parameter.

**Comment by SeppPenner** [comment]
Sorry, don't ask me why but I totally missed this one...

**Comment by SeppPenner** [comment]
Thank you for the finding, I fixed it.

**Comment by SeppPenner** [comment]
@all-contributors please add @danergo for tests

**Comment by SeppPenner** [comment]
@all-contributors please add @SeppPenner for code doc example maintenance projectManagement test
