### ISSUE TITLE
SetPersistentKeyName function seems invalid

### ISSUE THREAD

**Issue by danergo** [SeppPenner/WindowsHello#7]
Because it needs an instance.

However, during instance creation (by `CreateInstance`) you are creating the persistent key with the default name.

Then, `CreateInstance` creates a new `WinHelloProvider`, which stores `PersistentKeyName` to `currentKeyName`.

And both `Encrypt` and `PromptToDecrypt` is using `currentKeyName`, which only get's its value in `WinHelloProvider`'s constructor.

You shall either:

- update `currentKeyName` in `SetPersistentKeyName` function, or
- move the key creation to encrypt & decrypt functions, or
- extend the createinstance and constructor with the keyname parameter.

**Comment by SeppPenner** [comment]
Need to check this.

**Comment by SeppPenner** [comment]
Can you maybe provide a test scenario for this to help me understand the problem in detail?

**Comment by SeppPenner** [comment]
Closing this as pretty much unclear.
